name: DB

on:
  push:
    branches: [ develop, main ]
    paths:
      - 'bot_srcs/database/**'
      - 'bot_srcs/db_test.py'

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9 #install the python needed
          
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run tests
        run: |
          cd bot_srcs
          python db_test.py
